version: '3'

networks:
  kafka-net:
    driver: bridge
volumes:
  data01:
   driver: local
services: 
  zookeeper-server:
    image: bitnami/zookeeper:latest
    networks:
      - kafka-net
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    networks:
      - kafka-net    
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.6:9092
      - KAFKA_CFG_LISTENERS:PLAINTEXT://0.0.0.0:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server
  fluentd:
    build: .
    networks: 
      - kafka-net    
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./logs:/home/logs
    ports:
      - 24224:24224
      - 24224:24224/udp
    depends_on: 
      - kafka
    links:
      - elasticsearch
      - kafka
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: elasticsearch
    environment:
      discovery.type: single-node
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - kafka-net
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    environment: 
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on: 
      - elasticsearch
    links:
      - elasticsearch
    networks:
      - kafka-net
