version: '3'

networks:
  kafka-net:
    driver: bridge
volumes:
  data01:
   driver: local
services: 
  zookeeper:
    image: 'confluentinc/cp-zookeeper:3.1.1'
    container_name: zookeeper
    networks:
      - kafka-net
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
  kafka:
    image: 'confluentinc/cp-kafka:3.1.1'
    container_name: kafka
    networks:
      - kafka-net
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
  fluentd:
    build: .
    networks: 
      - kafka-net    
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - 24224:24224
      - 24224:24224/udp
    depends_on: 
      - kafka
    links:
      - elasticsearch
      - kafka
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: elasticsearch
    environment:
      discovery.type: single-node
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - kafka-net
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    environment: 
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on: 
      - elasticsearch
    links:
      - elasticsearch
    networks:
      - kafka-net
